'use client';

import { useState } from 'react';
import { Download, FileText, Image, Loader2, Check } from 'lucide-react';
import { ScanResult } from '@/lib/types';

interface ExportReportProps {
    scanResult: ScanResult;
    narrative: string;
    isVerified?: boolean;
    onVerify?: () => void;
}

export default function ExportReport({ scanResult, narrative, isVerified = false, onVerify }: ExportReportProps) {
    const [isExporting, setIsExporting] = useState(false);
    const [exportSuccess, setExportSuccess] = useState(false);

    const generateTextReport = () => {
        const report = `
═══════════════════════════════════════════════════════════════
                    THE DIGITAL SHADOW
                  Security Assessment Report
═══════════════════════════════════════════════════════════════

Generated: ${new Date().toLocaleString()}
Target: ${scanResult.query}
Risk Score: ${scanResult.riskScore}/100 (${scanResult.riskScore >= 70 ? 'CRITICAL' : scanResult.riskScore >= 50 ? 'HIGH' : 'MODERATE'})

───────────────────────────────────────────────────────────────
                     DATA BREACHES FOUND
───────────────────────────────────────────────────────────────
${scanResult.breaches.length > 0
                ? scanResult.breaches.map(b => `
• ${b.name} (${b.domain})
  Date: ${b.breachDate}
  Exposed Data: ${b.dataClasses.join(', ')}
  Affected Records: ${b.pwnCount.toLocaleString()}
`).join('')
                : 'No breaches found.'}

───────────────────────────────────────────────────────────────
                    PUBLIC PROFILES FOUND
───────────────────────────────────────────────────────────────
${scanResult.profiles.length > 0
                ? scanResult.profiles.map(p => `
• ${p.platform}
  URL: ${p.url}
`).join('')
                : 'No public profiles found.'}

───────────────────────────────────────────────────────────────
                      RISK BREAKDOWN
───────────────────────────────────────────────────────────────
Breach Exposure:        +${scanResult.riskBreakdown.breachExposure}
Social Media Visibility: +${scanResult.riskBreakdown.socialMediaVisibility}
Contact Info Leakage:   +${scanResult.riskBreakdown.contactInfoLeakage}
Location Data:          +${scanResult.riskBreakdown.locationData}
Passwords Exposed:      ${scanResult.riskBreakdown.passwordsExposed ? 'YES ⚠️' : 'No'}

───────────────────────────────────────────────────────────────
                    ATTACKER'S PLAYBOOK
───────────────────────────────────────────────────────────────
${narrative || 'Narrative not available.'}

───────────────────────────────────────────────────────────────
                     RECOMMENDATIONS
───────────────────────────────────────────────────────────────
${scanResult.riskBreakdown.passwordsExposed ? '⚠️ CRITICAL: Change all passwords immediately!\n' : ''}
1. Enable two-factor authentication on all accounts
2. Use a password manager with unique passwords
3. Review privacy settings on social media
4. Monitor accounts for suspicious activity
5. Be vigilant for phishing attempts

═══════════════════════════════════════════════════════════════
             Report generated by The Digital Shadow
                 Educational purposes only
═══════════════════════════════════════════════════════════════
`;
        return report;
    };

    const handleExport = async (format: 'text' | 'json') => {
        setIsExporting(true);

        try {
            let content: string;
            let filename: string;
            let mimeType: string;

            if (format === 'text') {
                content = generateTextReport();
                filename = `digital-shadow-report-${Date.now()}.txt`;
                mimeType = 'text/plain';
            } else {
                content = JSON.stringify({
                    generatedAt: new Date().toISOString(),
                    scanResult,
                    narrative,
                }, null, 2);
                filename = `digital-shadow-report-${Date.now()}.json`;
                mimeType = 'application/json';
            }

            // Create and download file
            const blob = new Blob([content], { type: mimeType });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = filename;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);

            setExportSuccess(true);
            setTimeout(() => setExportSuccess(false), 3000);
        } catch (error) {
            console.error('Export failed:', error);
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <div className="cyber-glass p-6">
            <div className="flex items-center gap-3 mb-3">
                <Download className="w-4 h-4 text-cyan-400" />
                <h3 className="text-sm font-semibold text-white">Export Report</h3>
            </div>

            <div className="relative">
                <div className={`flex gap-2 transition-all duration-700 ${!isVerified ? 'blur-sm grayscale select-none pointer-events-none' : ''}`}>
                    <button
                        onClick={() => handleExport('text')}
                        disabled={isExporting}
                        className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-cyan-500/20 text-cyan-400 rounded text-xs hover:bg-cyan-500/30 transition-colors disabled:opacity-50"
                    >
                        {isExporting ? (
                            <Loader2 className="w-3 h-3 animate-spin" />
                        ) : exportSuccess ? (
                            <Check className="w-3 h-3" />
                        ) : (
                            <FileText className="w-3 h-3" />
                        )}
                        Text Report
                    </button>
                    <button
                        onClick={() => handleExport('json')}
                        disabled={isExporting}
                        className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-purple-500/20 text-purple-400 rounded text-xs hover:bg-purple-500/30 transition-colors disabled:opacity-50"
                    >
                        {isExporting ? (
                            <Loader2 className="w-3 h-3 animate-spin" />
                        ) : (
                            <FileText className="w-3 h-3" />
                        )}
                        JSON Data
                    </button>
                </div>

                {/* Locked Overlay */}
                {!isVerified && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/40 backdrop-blur-[2px] rounded z-10 p-2">
                        <button
                            onClick={onVerify}
                            className="w-full h-full flex items-center justify-center gap-2 text-xs font-bold text-cyan-400 hover:text-cyan-300 transition-colors group"
                        >
                            <Download className="w-3 h-3 group-hover:scale-110 transition-transform" />
                            Verify to Unlock Export
                        </button>
                    </div>
                )}
            </div>

            <p className="text-xs text-gray-500 mt-2 text-center">
                Download your security assessment
            </p>
        </div>
    );
}
